#sudo docker-compose -f docker-compose-test.yml up
version: '3.3'

services:
  postgres:
    image: postgres:11.4
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 15432:5432
    command: [ "postgres", "-c", "log_statement=all" ]