"""receipt msg column

Revision ID: 0c01cfce0c7c
Revises: f9910ba1727d
Create Date: 2021-08-19 17:34:06.474042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c01cfce0c7c'
down_revision = 'f9910ba1727d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('msg_id', sa.Integer(), nullable=False))
    op.create_index('ix_receipt_msg_id', 'receipt', ['msg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_receipt_msg_id', table_name='receipt')
    op.drop_column('receipt', 'msg_id')
    # ### end Alembic commands ###
