"""init

Revision ID: 42cfcd9370dc
Revises: 
Create Date: 2021-06-08 14:43:37.190247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42cfcd9370dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.String(length=16), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.Enum('ADMIN', 'MANAGER', 'USER', name='permission'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cat_id', 'transaction', ['category_id'], unique=False)
    op.create_index('ix_tx_date', 'transaction', ['date'], unique=False)
    op.create_table('user_bot_state',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=48), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_bot_state')
    op.drop_index('ix_tx_date', table_name='transaction')
    op.drop_index('ix_cat_id', table_name='transaction')
    op.drop_table('transaction')
    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###
