"""order columns

Revision ID: 8f425d9262d3
Revises: 0ce3fb63c3f0
Create Date: 2021-08-12 18:29:30.327358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f425d9262d3'
down_revision = '0ce3fb63c3f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('utf_icon', sa.String(length=3), nullable=True))
    op.add_column('category', sa.Column('ui_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'ui_order')
    op.drop_column('category', 'utf_icon')
    # ### end Alembic commands ###
