"""delete transaction

Revision ID: 97f23256fbc4
Revises: 0e8401ec95e5
Create Date: 2021-06-11 21:29:09.586821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f23256fbc4'
down_revision = '0e8401ec95e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('msg_id', sa.Integer(), nullable=False))
    op.alter_column('transaction', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_user_msg', 'transaction', ['user_id', 'msg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_msg', table_name='transaction')
    op.alter_column('transaction', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('transaction', 'msg_id')
    # ### end Alembic commands ###
