"""receipt table

Revision ID: f9910ba1727d
Revises: 3e4f995bef95
Create Date: 2021-08-19 17:08:29.316216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9910ba1727d'
down_revision = '3e4f995bef95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt',
    sa.Column('tx_id', sa.Integer(), nullable=False),
    sa.Column('file_number', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['tx_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('tx_id', 'file_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipt')
    # ### end Alembic commands ###
