name: zap_scan

on:
  pull_request: {}
  push:
    branches: ["master", "main"]
  schedule:
    - cron: '22 11 * * *'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://www.zaproxy.org/'
#          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'